.TH "src/config.hpp" 3 "Version 0.1.0" "passengercpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/config.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBnum_default\fP   unsigned int"
.br
.RI "The default numeric type for templates\&. "
.ti -1c
.RI "#define \fBnum_non_default\fP   int"
.br
.RI "The additional non default replacement numeric type for templates\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define num_default   unsigned int"

.PP
The default numeric type for templates\&. 
.PP
Definition at line \fB6\fP of file \fBconfig\&.hpp\fP\&.
.SS "#define num_non_default   int"

.PP
The additional non default replacement numeric type for templates\&. 
.PP
Definition at line \fB8\fP of file \fBconfig\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for passengercpp from the source code\&.
