.TH "src/graph.hpp" 3 "Version 0.1.0" "passengercpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/graph.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br
\fR#include 'passenger\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraph< NodeT >\fP"
.br
.RI "The simple graph's class\&. Stores all nodes of the type \fRNodeT*\fP and points also to a single start and a single end node\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for passengercpp from the source code\&.
