.TH "src/passenger.cpp" 3 "Version 0.1.0" "passengercpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/passenger.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'passenger\&.hpp'\fP
.br
\fR#include 'edge\&.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRange\fP"
.br
.ti -1c
.RI "\fBRange< num_non_default >\fP"
.br
.ti -1c
.RI "\fBNumberEnumeration\fP"
.br
.ti -1c
.RI "\fBNumberEnumeration< num_non_default >\fP"
.br
.ti -1c
.RI "\fBPassengerNumber\fP"
.br
.ti -1c
.RI "\fBPassengerNumber< num_non_default >\fP"
.br
.ti -1c
.RI "\fBNode\fP"
.br
.ti -1c
.RI "\fBNode< GraphPassengerNumber<> >\fP"
.br
.ti -1c
.RI "\fBNode< GraphPassengerNumber< num_non_default > >\fP"
.br
.ti -1c
.RI "\fBNodeNumbered< GraphPassengerNumber<> >\fP"
.br
.ti -1c
.RI "\fBNodeNumbered< GraphPassengerNumber< num_non_default >, num_non_default >\fP"
.br
.ti -1c
.RI "\fBPassengerNode< GraphPassenger, EdgeSimple<> >\fP"
.br
.ti -1c
.RI "\fBPassengerNode< GraphPassenger, EdgeSimple<>, num_non_default >\fP"
.br
.ti -1c
.RI "\fBPassengerNodeActional< GraphPassenger, EdgeSimple<>, num_default >\fP"
.br
.ti -1c
.RI "\fBPassengerNodeActional< GraphPassengerNumber<>, EdgeSimple<>, num_default >\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Node"

.PP
Definition at line \fB1\fP of file \fBpassenger\&.cpp\fP\&.
.SS "\fBNode\fP< \fBGraphPassengerNumber\fP< \fBnum_non_default\fP > >"

.PP
Definition at line \fB1\fP of file \fBpassenger\&.cpp\fP\&.
.SS "\fBNode\fP< \fBGraphPassengerNumber\fP<> >"

.PP
Definition at line \fB1\fP of file \fBpassenger\&.cpp\fP\&.
.SS "\fBNodeNumbered\fP< \fBGraphPassengerNumber\fP< \fBnum_non_default\fP >, \fBnum_non_default\fP >"

.PP
Definition at line \fB1\fP of file \fBpassenger\&.cpp\fP\&.
.SS "\fBNodeNumbered\fP< \fBGraphPassengerNumber\fP<> >"

.PP
Definition at line \fB1\fP of file \fBpassenger\&.cpp\fP\&.
.SS "NumberEnumeration"

.PP
Definition at line \fB1\fP of file \fBpassenger\&.cpp\fP\&.
.SS "\fBNumberEnumeration\fP< \fBnum_non_default\fP >"

.PP
Definition at line \fB1\fP of file \fBpassenger\&.cpp\fP\&.
.SS "\fBPassengerNode\fP< \fBGraphPassenger\fP, \fBEdgeSimple\fP<> >"

.PP
Definition at line \fB1\fP of file \fBpassenger\&.cpp\fP\&.
.SS "\fBPassengerNode\fP< \fBGraphPassenger\fP, \fBEdgeSimple\fP<>, \fBnum_non_default\fP >"

.PP
Definition at line \fB1\fP of file \fBpassenger\&.cpp\fP\&.
.SS "\fBPassengerNodeActional\fP< \fBGraphPassenger\fP, \fBEdgeSimple\fP<>, \fBnum_default\fP >"

.PP
Definition at line \fB1\fP of file \fBpassenger\&.cpp\fP\&.
.SS "\fBPassengerNodeActional\fP< \fBGraphPassengerNumber\fP<>, \fBEdgeSimple\fP<>, \fBnum_default\fP >"

.PP
Definition at line \fB1\fP of file \fBpassenger\&.cpp\fP\&.
.SS "PassengerNumber"

.PP
Definition at line \fB1\fP of file \fBpassenger\&.cpp\fP\&.
.SS "\fBPassengerNumber\fP< \fBnum_non_default\fP >"

.PP
Definition at line \fB1\fP of file \fBpassenger\&.cpp\fP\&.
.SS "Range"

.PP
Definition at line \fB1\fP of file \fBpassenger\&.cpp\fP\&.
.SS "\fBRange\fP< \fBnum_non_default\fP >"

.PP
Definition at line \fB1\fP of file \fBpassenger\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for passengercpp from the source code\&.
