.TH "Range< num >" 3 "Version 0.1.0" "passengercpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Range< num > \- A numeric range with a templated numeric type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <passenger\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBRange\fP (const num start, const num end)"
.br
.RI "The constructor\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const num \fBfrom\fP"
.br
.RI "The lower range's number\&. "
.ti -1c
.RI "const num \fBto\fP"
.br
.RI "The upper range's number\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename num = num_default>
.br
class Range< num >"A numeric range with a templated numeric type\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fInum\fP The numeric type of the range's number\&. 
.RE
.PP

.PP
Definition at line \fB15\fP of file \fBpassenger\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename num  = num_default> virtual \fBRange\fP< num >\fB::Range\fP (const num start, const num end)\fR [inline]\fP, \fR [virtual]\fP"

.PP
The constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIstart\fP The lower range's number 
.br
\fIend\fP The upper range's number 
.RE
.PP

.PP
Definition at line \fB25\fP of file \fBpassenger\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename num  = num_default> const num \fBRange\fP< num >::from"

.PP
The lower range's number\&. 
.PP
Definition at line \fB18\fP of file \fBpassenger\&.hpp\fP\&.
.SS "template<typename num  = num_default> const num \fBRange\fP< num >::to"

.PP
The upper range's number\&. 
.PP
Definition at line \fB20\fP of file \fBpassenger\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for passengercpp from the source code\&.
